version: '3.9'

services:
  core:
    image: razvantanase/core:1.0.0
    depends_on:
      - io
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first
    networks:
      - internal
      - io_core
      - auth_core

  io:
    image: razvantanase/io:1.0.0
    depends_on:
      - db_backend
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first
    networks:
      - io_core
      - io_db_backend

  auth:
    image: razvantanase/auth:1.0.0
    depends_on:
      - db_auth
    networks:
      - auth_core
      - auth_db_auth

  db_backend:
    image: mysql:8.0.33
    volumes:
      - db_backend:/var/lib/mysql
    user: root
    environment:
      - MYSQL_DATABASE=connectville-app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - io_db_backend
      - workbench_db_backend

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db_backend
      - db_auth
    networks:
      - internal
      - workbench_db_auth
      - workbench_db_backend

  db_auth:
    image: mysql:8.0.33
    volumes:
      - db_auth:/var/lib/mysql
    user: root
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    networks:
      - auth_db_auth
      - workbench_db_auth

  kong:
    image: kong:latest
    volumes:
      - ./Kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
      - "8444:8444"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - internal

volumes:
  db_backend:
  db_auth:

networks:
  internal:
  io_core:
  io_db_backend:
  auth_core:
  auth_db_auth:
  workbench_db_auth:
  workbench_db_backend: